// Pure, build-time-only helpers for turning Yahoo Finance chart responses
// into the committed src/data/quotes.ts module that feeds the ticker-tape
// frame. No network, no filesystem: scripts/generate-quotes-data.ts owns the
// side effects.

export type TapeQuote = {
	/** Display symbol on the tape (the real exchange ticker). */
	sym: string;
	/** Day change vs previous close, in percent, rounded to 2 decimals. */
	deltaPct: number;
	/** Day high / low in the instrument's own currency. */
	high: number;
	low: number;
	/** Day volume in instrument units. */
	volume: number;
};

/** One tape entry to fetch: the display symbol + its Yahoo Finance symbol. */
export type QuoteSource = { sym: string; yahoo: string };

export function chartUrl(source: QuoteSource): string {
	return `https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(
		source.yahoo,
	)}?range=1d&interval=1d`;
}

const round2 = (n: number) => Math.round(n * 100) / 100;

/**
 * Digs one TapeQuote out of a Yahoo v8 chart response's meta block. Returns
 * null (with a warning naming the missing field) on any absent/non-finite
 * number - a malformed instrument is skipped, never written as NaN.
 */
export function parseQuoteMeta(sym: string, json: unknown): TapeQuote | null {
	const skip = (field: string) => {
		console.warn(`quotesFeed: skipping ${sym}: missing ${field}`);
		return null;
	};
	const meta = (
		json as {
			chart?: { result?: { meta?: Record<string, unknown> }[] };
		}
	)?.chart?.result?.[0]?.meta;
	if (!meta) return skip("chart.result[0].meta");

	const num = (field: string): number | null => {
		const v = meta[field];
		return typeof v === "number" && Number.isFinite(v) ? v : null;
	};
	const price = num("regularMarketPrice");
	if (price === null) return skip("regularMarketPrice");
	const prev = num("chartPreviousClose") ?? num("previousClose");
	if (prev === null || prev === 0) return skip("chartPreviousClose");
	const high = num("regularMarketDayHigh");
	if (high === null) return skip("regularMarketDayHigh");
	const low = num("regularMarketDayLow");
	if (low === null) return skip("regularMarketDayLow");
	const volume = num("regularMarketVolume");
	if (volume === null) return skip("regularMarketVolume");

	return {
		sym,
		deltaPct: round2(((price - prev) / prev) * 100),
		high: round2(high),
		low: round2(low),
		volume: Math.round(volume),
	};
}

const delay = (ms: number) => new Promise((r) => setTimeout(r, ms));

// Yahoo rate-limits bot-looking requests, and (verified live) a FULL fake
// Chrome UA string trips its 429 heuristic where the bare token passes - so
// send exactly "Mozilla/5.0", and retry with linear backoff before failing
// loud. Network happens only through the injected fetchImpl, keeping this
// testable without the wire.
const BROWSER_USER_AGENT = "Mozilla/5.0";

export async function fetchQuoteJson(
	fetchImpl: typeof fetch,
	url: string,
	opts?: { attempts?: number; timeoutMs?: number; delayMs?: number },
): Promise<unknown> {
	const attempts = opts?.attempts ?? 4;
	const timeoutMs = opts?.timeoutMs ?? 15_000;
	const delayMs = opts?.delayMs ?? 800;
	let lastFailure = "";
	for (let attempt = 1; attempt <= attempts; attempt++) {
		try {
			const res = await fetchImpl(url, {
				headers: { "User-Agent": BROWSER_USER_AGENT },
				signal: AbortSignal.timeout(timeoutMs),
			});
			if (res.ok) return await res.json();
			lastFailure = `HTTP ${res.status} ${res.statusText}`;
		} catch (error) {
			lastFailure = error instanceof Error ? error.message : String(error);
		}
		if (attempt < attempts) await delay(delayMs * attempt);
	}
	throw new Error(
		`Quote request failed after ${attempts} attempts: ${lastFailure}`,
	);
}

// Every string field goes through JSON.stringify so symbols always land as
// valid TypeScript string literals; numbers are emitted bare.
export function renderQuotesModule(quotes: TapeQuote[], asOf: string): string {
	const entries = quotes
		.map(
			(q) =>
				`\t{\n` +
				`\t\tsym: ${JSON.stringify(q.sym)},\n` +
				`\t\tdeltaPct: ${q.deltaPct},\n` +
				`\t\thigh: ${q.high},\n` +
				`\t\tlow: ${q.low},\n` +
				`\t\tvolume: ${q.volume},\n` +
				`\t},\n`,
		)
		.join("");
	return (
		`// AUTO-GENERATED by scripts/generate-quotes-data.ts. Do not edit by hand.\n` +
		`// Regenerate with: bun run generate:quotes\n\n` +
		`export interface TapeQuote {\n` +
		`\tsym: string;\n` +
		`\tdeltaPct: number;\n` +
		`\thigh: number;\n` +
		`\tlow: number;\n` +
		`\tvolume: number;\n` +
		`}\n\n` +
		`/** Trading day the quotes were captured (build date, YYYY-MM-DD). */\n` +
		`export const TAPE_AS_OF = ${JSON.stringify(asOf)};\n\n` +
		`export const TAPE_QUOTES: TapeQuote[] = [\n${entries}];\n`
	);
}
