// Pure, build-time-only helpers for turning the public YouTube channel RSS
// feed into the committed src/data/youtubeShorts.ts module. No network, no
// filesystem: scripts/generate-shorts-data.ts owns the side effects.

export type ShortEntry = {
	id: string;
	title: string;
	views: number;
	publishedAt: string;
};

const NAMED_ENTITIES: Record<string, string> = {
	amp: "&",
	lt: "<",
	gt: ">",
	quot: '"',
	apos: "'",
};

// Single non-recursive pass: "&amp;amp;" decodes to "&amp;", never to "&".
export function decodeXmlEntities(s: string): string {
	return s.replace(
		/&(?:(amp|lt|gt|quot|apos)|#(\d+)|#x([0-9a-fA-F]+));/g,
		(match, named?: string, dec?: string, hex?: string) => {
			if (named) return NAMED_ENTITIES[named] ?? match;
			if (dec) return String.fromCodePoint(Number.parseInt(dec, 10));
			if (hex) return String.fromCodePoint(Number.parseInt(hex, 16));
			return match;
		},
	);
}

function firstMatch(chunk: string, re: RegExp): string | undefined {
	return re.exec(chunk)?.[1];
}

// Splits the feed on <entry>; chunk 0 is the channel-level preamble (it holds
// a channel <title>, not a video) and is never parsed as an entry. Malformed
// entries are skipped with a warning naming the 0-based entry index and the
// missing field; valid entries are sorted newest-first by publishedAt.
export function parseShortsFeed(xml: string): ShortEntry[] {
	const chunks = xml.split("<entry>").slice(1);
	const entries: ShortEntry[] = [];
	chunks.forEach((chunk, index) => {
		const skip = (field: string) =>
			console.warn(`shortsFeed: skipping entry ${index}: missing ${field}`);
		const id = firstMatch(chunk, /<yt:videoId>([^<]+)<\/yt:videoId>/);
		if (!id) {
			skip("yt:videoId");
			return;
		}
		const rawTitle = firstMatch(chunk, /<title>([^<]+)<\/title>/);
		if (!rawTitle) {
			skip("title");
			return;
		}
		const publishedAt = firstMatch(chunk, /<published>([^<]+)<\/published>/);
		if (!publishedAt) {
			skip("published");
			return;
		}
		const views = firstMatch(chunk, /<media:statistics views="(\d+)"/);
		if (!views) {
			skip("media:statistics views");
			return;
		}
		entries.push({
			id,
			title: decodeXmlEntities(rawTitle),
			views: Number.parseInt(views, 10),
			publishedAt,
		});
	});
	return entries.sort(
		(a, b) => Date.parse(b.publishedAt) - Date.parse(a.publishedAt),
	);
}

const delay = (ms: number) => new Promise((r) => setTimeout(r, ms));

// YouTube serves the feed a 4xx/5xx to requests without a browser-like
// User-Agent (bot heuristic, harsher from datacenter IPs like a CI/deploy
// host), so we always send one. On top of that the endpoint is genuinely
// flaky, so retry with linear backoff before failing loud. Network happens
// only through the injected fetchImpl, keeping this testable without the wire.
const BROWSER_USER_AGENT =
	"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

export async function fetchFeedXml(
	fetchImpl: typeof fetch,
	url: string,
	opts?: { attempts?: number; timeoutMs?: number; delayMs?: number },
): Promise<string> {
	const attempts = opts?.attempts ?? 5;
	const timeoutMs = opts?.timeoutMs ?? 15_000;
	const delayMs = opts?.delayMs ?? 800;
	let lastFailure = "";
	for (let attempt = 1; attempt <= attempts; attempt++) {
		try {
			const res = await fetchImpl(url, {
				headers: { "User-Agent": BROWSER_USER_AGENT },
				signal: AbortSignal.timeout(timeoutMs),
			});
			if (res.ok) return await res.text();
			lastFailure = `HTTP ${res.status} ${res.statusText}`;
		} catch (error) {
			lastFailure = error instanceof Error ? error.message : String(error);
		}
		if (attempt < attempts) await delay(delayMs * attempt);
	}
	throw new Error(
		`Shorts feed request failed after ${attempts} attempts: ${lastFailure}`,
	);
}

// Every string field goes through JSON.stringify so quotes, backslashes and
// unicode in titles always land as valid TypeScript string literals.
export function renderShortsModule(shorts: ShortEntry[]): string {
	const entries = shorts
		.map(
			(short) =>
				`\t{\n` +
				`\t\tid: ${JSON.stringify(short.id)},\n` +
				`\t\ttitle: ${JSON.stringify(short.title)},\n` +
				`\t\tviews: ${short.views},\n` +
				`\t\tpublishedAt: ${JSON.stringify(short.publishedAt)},\n` +
				`\t},\n`,
		)
		.join("");
	return (
		`// AUTO-GENERATED by scripts/generate-shorts-data.ts. Do not edit by hand.\n` +
		`// Regenerate with: bun run generate:shorts\n\n` +
		`export interface YoutubeShort {\n` +
		`\tid: string;\n` +
		`\ttitle: string;\n` +
		`\tviews: number;\n` +
		`\tpublishedAt: string;\n` +
		`}\n\n` +
		`export const YOUTUBE_SHORTS: YoutubeShort[] = [\n${entries}];\n`
	);
}
