/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutTeachingRouteImport } from './routes/_layout.teaching'
import { Route as LayoutMusicRouteImport } from './routes/_layout.music'
import { Route as LayoutLearningRouteImport } from './routes/_layout.learning'
import { Route as LayoutFamilyRouteImport } from './routes/_layout.family'
import { Route as LayoutCareerRouteImport } from './routes/_layout.career'
import { Route as LayoutProjectsSlugRouteImport } from './routes/_layout.projects.$slug'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeachingRoute = LayoutTeachingRouteImport.update({
  id: '/teaching',
  path: '/teaching',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMusicRoute = LayoutMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLearningRoute = LayoutLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFamilyRoute = LayoutFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCareerRoute = LayoutCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsSlugRoute = LayoutProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/career': typeof LayoutCareerRoute
  '/family': typeof LayoutFamilyRoute
  '/learning': typeof LayoutLearningRoute
  '/music': typeof LayoutMusicRoute
  '/teaching': typeof LayoutTeachingRoute
  '/projects/$slug': typeof LayoutProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/career': typeof LayoutCareerRoute
  '/family': typeof LayoutFamilyRoute
  '/learning': typeof LayoutLearningRoute
  '/music': typeof LayoutMusicRoute
  '/teaching': typeof LayoutTeachingRoute
  '/': typeof LayoutIndexRoute
  '/projects/$slug': typeof LayoutProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/career': typeof LayoutCareerRoute
  '/_layout/family': typeof LayoutFamilyRoute
  '/_layout/learning': typeof LayoutLearningRoute
  '/_layout/music': typeof LayoutMusicRoute
  '/_layout/teaching': typeof LayoutTeachingRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/projects/$slug': typeof LayoutProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/career'
    | '/family'
    | '/learning'
    | '/music'
    | '/teaching'
    | '/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/career'
    | '/family'
    | '/learning'
    | '/music'
    | '/teaching'
    | '/'
    | '/projects/$slug'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/career'
    | '/_layout/family'
    | '/_layout/learning'
    | '/_layout/music'
    | '/_layout/teaching'
    | '/_layout/'
    | '/_layout/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teaching': {
      id: '/_layout/teaching'
      path: '/teaching'
      fullPath: '/teaching'
      preLoaderRoute: typeof LayoutTeachingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/music': {
      id: '/_layout/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof LayoutMusicRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/learning': {
      id: '/_layout/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LayoutLearningRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/family': {
      id: '/_layout/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof LayoutFamilyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/career': {
      id: '/_layout/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof LayoutCareerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$slug': {
      id: '/_layout/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof LayoutProjectsSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutCareerRoute: typeof LayoutCareerRoute
  LayoutFamilyRoute: typeof LayoutFamilyRoute
  LayoutLearningRoute: typeof LayoutLearningRoute
  LayoutMusicRoute: typeof LayoutMusicRoute
  LayoutTeachingRoute: typeof LayoutTeachingRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProjectsSlugRoute: typeof LayoutProjectsSlugRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCareerRoute: LayoutCareerRoute,
  LayoutFamilyRoute: LayoutFamilyRoute,
  LayoutLearningRoute: LayoutLearningRoute,
  LayoutMusicRoute: LayoutMusicRoute,
  LayoutTeachingRoute: LayoutTeachingRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProjectsSlugRoute: LayoutProjectsSlugRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
