// AUTO-GENERATED by scripts/generate-quotes-data.ts. Do not edit by hand.
// Regenerate with: bun run generate:quotes

export interface TapeQuote {
	sym: string;
	deltaPct: number;
	high: number;
	low: number;
	volume: number;
}

/** Trading day the quotes were captured (build date, YYYY-MM-DD). */
export const TAPE_AS_OF = "2026-08-02";

export const TAPE_QUOTES: TapeQuote[] = [
	{
		sym: "VWCE",
		deltaPct: 0.58,
		high: 164.36,
		low: 162.46,
		volume: 278452,
	},
	{
		sym: "AAPL",
		deltaPct: -7.35,
		high: 310.69,
		low: 300,
		volume: 132489137,
	},
	{
		sym: "NVDA",
		deltaPct: 2.93,
		high: 201.97,
		low: 194.95,
		volume: 139961152,
	},
	{
		sym: "BTC",
		deltaPct: 0.94,
		high: 63521.16,
		low: 62751.01,
		volume: 15017825280,
	},
	{
		sym: "MSFT",
		deltaPct: 3.02,
		high: 466.84,
		low: 449.55,
		volume: 60845971,
	},
	{
		sym: "ETH",
		deltaPct: 1.77,
		high: 1880.4,
		low: 1842.18,
		volume: 5670557184,
	},
	{
		sym: "TSLA",
		deltaPct: 0.76,
		high: 315.5,
		low: 301.97,
		volume: 36630560,
	},
	{
		sym: "EUNL",
		deltaPct: 0.51,
		high: 125.2,
		low: 123.96,
		volume: 381942,
	},
];
