// AUTO-GENERATED by scripts/generate-quotes-data.ts. Do not edit by hand.
// Regenerate with: bun run generate:quotes

export interface TapeQuote {
	sym: string;
	deltaPct: number;
	high: number;
	low: number;
	volume: number;
}

/** Trading day the quotes were captured (build date, YYYY-MM-DD). */
export const TAPE_AS_OF = "2026-07-17";

export const TAPE_QUOTES: TapeQuote[] = [
	{
		sym: "VWCE",
		deltaPct: -1.68,
		high: 163.26,
		low: 162.68,
		volume: 108729,
	},
	{
		sym: "AAPL",
		deltaPct: 1.76,
		high: 334.68,
		low: 326.79,
		volume: 62673782,
	},
	{
		sym: "NVDA",
		deltaPct: -2.4,
		high: 211.08,
		low: 205.85,
		volume: 116253420,
	},
	{
		sym: "BTC",
		deltaPct: -1.57,
		high: 63964.58,
		low: 62632.32,
		volume: 27927222272,
	},
	{
		sym: "MSFT",
		deltaPct: 1.38,
		high: 405.99,
		low: 392.05,
		volume: 34338326,
	},
	{
		sym: "ETH",
		deltaPct: -1.87,
		high: 1867.18,
		low: 1820.7,
		volume: 11579981824,
	},
	{
		sym: "TSLA",
		deltaPct: -0.86,
		high: 395.31,
		low: 385.32,
		volume: 28935215,
	},
	{
		sym: "EUNL",
		deltaPct: -1.41,
		high: 124.85,
		low: 124.47,
		volume: 88708,
	},
];
