// AUTO-GENERATED by scripts/generate-quotes-data.ts. Do not edit by hand.
// Regenerate with: bun run generate:quotes

export interface TapeQuote {
	sym: string;
	deltaPct: number;
	high: number;
	low: number;
	volume: number;
}

/** Trading day the quotes were captured (build date, YYYY-MM-DD). */
export const TAPE_AS_OF = "2026-07-20";

export const TAPE_QUOTES: TapeQuote[] = [
	{
		sym: "VWCE",
		deltaPct: 0.42,
		high: 164.62,
		low: 163.24,
		volume: 248564,
	},
	{
		sym: "AAPL",
		deltaPct: -2.14,
		high: 333.71,
		low: 323.7,
		volume: 51014085,
	},
	{
		sym: "NVDA",
		deltaPct: 0.23,
		high: 207.74,
		low: 202.28,
		volume: 83734272,
	},
	{
		sym: "BTC",
		deltaPct: 0.54,
		high: 65703.08,
		low: 63765.35,
		volume: 30686312448,
	},
	{
		sym: "MSFT",
		deltaPct: 2.15,
		high: 403.18,
		low: 389.67,
		volume: 26734768,
	},
	{
		sym: "ETH",
		deltaPct: 1.35,
		high: 1913.49,
		low: 1845.54,
		volume: 12105924608,
	},
	{
		sym: "TSLA",
		deltaPct: -2.96,
		high: 386.49,
		low: 369.43,
		volume: 32893543,
	},
	{
		sym: "EUNL",
		deltaPct: 0.29,
		high: 125.6,
		low: 124.66,
		volume: 197738,
	},
];
