// AUTO-GENERATED by scripts/generate-shorts-data.ts. Do not edit by hand.
// Regenerate with: bun run generate:shorts

export interface YoutubeShort {
	id: string;
	title: string;
	views: number;
	publishedAt: string;
}

export const YOUTUBE_SHORTS: YoutubeShort[] = [
	{
		id: "YaoyTizlaE4",
		title: "Is it worth it Part 1",
		views: 243,
		publishedAt: "2026-05-11T07:55:48+00:00",
	},
	{
		id: "cgsF6B5eR98",
		title: "Magical CLI Tools - Part 1 #agenticcoding #coding #develop",
		views: 1015,
		publishedAt: "2026-05-09T15:11:22+00:00",
	},
	{
		id: "5mgQepVfcyc",
		title: "Day 3 -  Best tools for your tech stack - Part 1",
		views: 454,
		publishedAt: "2026-05-06T21:10:50+00:00",
	},
	{
		id: "UGgKyRGUwkE",
		title: "I see the issue now - Part 1",
		views: 959,
		publishedAt: "2026-05-05T22:17:30+00:00",
	},
	{
		id: "ueRlidFgFYY",
		title: "Agentic Coding - hello to Day 1 of 30",
		views: 743,
		publishedAt: "2026-05-05T00:27:20+00:00",
	},
];
